[package]
name = "pj_xxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wio_terminal = "0.3"
cortex-m = "0.7.3"
embedded-graphics = "0.6.2"
